"""empty message

Revision ID: 24e604a187a5
Revises: ecd75fd26d10
Create Date: 2023-03-29 12:34:46.596592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24e604a187a5"
down_revision = "ecd75fd26d10"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "document_rubric_document_id_fkey",
        "document_rubric",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "document_rubric",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_rubric", type_="foreignkey")
    op.create_foreign_key(
        "document_rubric_document_id_fkey",
        "document_rubric",
        "document",
        ["document_id"],
        ["id"],
    )
    # ### end Alembic commands ###
