"""empty message

Revision ID: ac926c493dcb
Revises: 24e604a187a5
Create Date: 2023-03-29 14:29:06.942612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac926c493dcb"
down_revision = "24e604a187a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
